### ISSUE TITLE
Comunicação interna

### ISSUE THREAD

**Issue by slinstj** [Yii-Brasil-Dev/definicoes#2]
Acho que seria interessante termos um canal privativo de comunicação para algumas circunstâncias, como por exemplo, decisões sobre projetos que vão ser iniciados, agendamento de algum tipo de reunião (se houver), e talvez outras possibilidades que não seria interessante que fosse deixadas públicas.

Gostaria de ouvir a opinião de vocês @Yii-Brasil-Dev/core e sugestões de recursos para essa finalidade, se a maioria for a favor. (Enquanto isso vamos discutindo no github mesmo)

**Comment by newerton** [comment]
@slinstj eu raramente uso o Whatsapp, Facebook e Telegram, mais por falta de tempo.
Uso o Whatsapp pelo Bluestack, e vi esses dias que tem o Software do Telegram pra instalar no PC.

O que uso diariamente, e o skype, esse é quase 100% para trabalho e amigos.

**Comment by ericmaicon** [comment]
Já procurei saber como funciona o core do Yii, mas não obtive sucesso (se tem algum canal no slack ou algo parecido). Gosto do Slack, mas pra mim qualquer meio está tranquilo (skype). Acho que realmente precisamos de algum meio privado, mas evitar discutir importantes regras lá. Afinal, issues tb entram como index no search do google e as vezes me salva de alguns bugs/implementações.

**Comment by slinstj** [comment]
Não uso muito Skype, mas parece que é o que ficaria mais em comum para o time, já que o ericmaicon também poderia usar. Creio que posso usar a versão web, já que permite texto ou a versão linux mesmo. Seria bom ser uma ferramenta que possamos deixar aberta na maior parte do dia, "on duty".

Outra sugestão seria o próprio chat do gmail (se ficar bom pra vc também newerton), porém não tenho certeza se é possível criar um grupo através dele.

Não precisa ser nada muito elaborado, basta ser possível conversar, de preferência com registro de histórico. 

Slack conheço muito pouco mas já vi a galera do laravel usando.

**Comment by newerton** [comment]
Bom. por mim qualquer um está válido.

Podemos usar o slack, usei ele em um Hackathon e não tiver problema.

**Comment by almirb** [comment]
Eu voto no Telegram ou no Skype.  Caso encontrem alguma forma mais eficiente, posso me adaptar também.  Ouvi falar bastante no Slack, mas nunca usei.

**Comment by newerton** [comment]
No Slack é possível ter Conferência? Por que tem questões que é melhor falar do que ficar digitando!

**Comment by ericmaicon** [comment]
Podemos ir de Skype. Fica aberto o dia inteiro aqui (os outros tb, por mim o que vocês escolherem tá valendo).

@newerton , slack usa o hangouts pra conferência.

**Comment by slinstj** [comment]
No caso do Slack, é possível deixar sempre ativo e receber notificações? Tem histórico?

**Comment by ericmaicon** [comment]
@slinstj 

Slack tem pra celular, desktop e web. Pode deixar sempre ativo.
Pode deixar público, pro povo se cadastrar por aqui e entrar nas salas. Podemos criar salas privadas tb.
Tem histórico também.

Independente da ferramenta, não podemos deixar de lado as discussões aqui. Só pra não ficar igual acontece hoje na comunidade com o telegram.

**Comment by slinstj** [comment]
Claro, concordo Eric, deveria ser usado somente para ocasiões específicas.

**Comment by slinstj** [comment]
Parece que a decisão vai ficar entre skype e slack. Eu voto pelo Slack, pela experiência nova. Se não atender, simplesmente trocamos. Podem dar seu voto final (espero que não dê empate rsss, precisamos de um quinto membro!).

**Comment by almirb** [comment]
Por mim, vamos de Slack... A não ser que alguém não possa utilizá-lo.

**Comment by slinstj** [comment]
Alguém mais aqui pra definirmos?

**Comment by ericmaicon** [comment]
https://github.com/outsideris/slack-invite-automation

Vou dar uma olhada nessas "ferramentas" para auto invitation e falo pra vcs (se confirmarem o slack).

**Comment by slinstj** [comment]
Está confortável com o slack também @newerton? Se sim, acho que temos um escolhido. E aí podemos fechar este issue.

**Comment by newerton** [comment]
@slinstj qualquer um é válido, o que precisamos ter é um histórico e conferência.

**Comment by slinstj** [comment]
Escolhido pela maioria:

- Slack: [eric, newerton, almir e sidney]

@ericmaicon, como já se disponibilizou, poderia cuidar da criação do time no slack pra nós, certo? Aguardamos seu convite lá.

Fechando o issue. Se necessário podem reabrir.

**Comment by ericmaicon** [comment]
https://code-on-yii.slack.com/x-43701562752-43655316067/signup

code-on já existia. Podemos trocar depois. Convidei todos menos o @newerton, não achei o email dele.

**Comment by newerton** [comment]
@ericmaicon o slack não permite eu participar de 2 team?

**Comment by ericmaicon** [comment]
@newerton permite. Eu to em 5. Mas você precisa meio que cadastrar um novo usuário e senha para aquele team. Pode usar o mesmo, desde que você passe pelo mesmo processo de cadastro.

**Comment by newerton** [comment]
Me add ae: newerton.araujo@gmail.com
